branches:
  - master
  - auto
  - try

host:
  distro: fedora/28/atomic
  specs:
    secondary-disk: 10

context: fedora/28/atomic

required: true

tests:
  - mkdir -p /srv/install
  - docker run --rm --privileged -v $PWD:/code -v /srv/install:/srv/install --workdir /code registry.fedoraproject.org/fedora:28 sh -c 'dnf install -y make && make install DESTDIR=/srv/install'
  - systemctl stop docker
  - rm -rf /var/lib/docker/*
  - ostree admin unlock
  - rsync -rlv /srv/install/usr/ /usr/
  - rsync -rlv /srv/install/etc/ /etc/
  - rm -f /etc/sysconfig/docker-storage-setup
  - rm -f /etc/sysconfig/docker-storage
  - if findmnt /dev/vdb; then umount /dev/vdb; fi
  - wipefs -a /dev/vdb
  - echo "DEVS=/dev/vdb" >> tests/css-test-config
  - tests/run-tests.sh

timeout: 15m

artifacts:
  - temp/logs.txt
