branches:
  - master
  - auto
  - try

host:
  distro: fedora/28/atomic
  specs:
    secondary-disk: 10

context: fedora/28/atomic

required: true

tests:
  - systemctl stop docker
  # just empty the dir, don't delete it (on F26, /var/lib/docker is an lv mount)
  - rm -rf /var/lib/docker/*
  - ostree admin unlock
  - make install
  - rm -f /etc/sysconfig/docker-storage-setup
  - rm -f /etc/sysconfig/docker-storage
  - if findmnt /dev/vdb; then umount /dev/vdb; fi
  - wipefs -a /dev/vdb
  - echo "DEVS=/dev/vdb" >> tests/css-test-config
  - tests/run-tests.sh

timeout: 15m

artifacts:
  - temp/logs.txt
